@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' LAYOUT_WITH_LEGEND()

title Архитектура 1С АСПСП

'Person(СпециалистЗУП, Бухгалтер по ЗП, "Специалист 1С:ЗУП")
Person(СотрудникТочкиПродаж, Продавец, "Сотрудник компании")
Person(Актуарий, Актуарий, "Сотрудник компании")
Person(СотрудникДФУ, Бухгалтер , "Сотрудник компании")

' Системы
System_Boundary(1С_АСПСП, "1C:АСПСП") {
    Container(НастройкиПродуктов, "Настройки продуктов для продаж", "")
    Container(ПредварительныйРасчет, "Предварительный расчет стоимости полисов", "")
    Container_Boundary(АС_Учет, "Учет договоров страхования и убытков", "") {
        Component(УчетДоговоровИДопСоглашений, "Учет договоров страхования и доп. соглашений",, "")
        Component(ОбменДаннымиПоПолисам, "Обмен информацией по проданным полисам",, "")
    }
}

System_Boundary(Бухгалтерия, "1C:Бухгалтерия") {
    Container(НСИ_БУ, "НСИ", "")
    Container(РеглУчетБП, "Регламентированный учет", "") {
        Component(ОтражениеПолисоввБУ, "Отражение полисов в бухучете", , "")
    }    
}

System_Boundary(УчетнаяСистема, "Учетная система полисов") {
    Container(НСИ, "НСИ", "")
    Container(УчетПолисов, "Регламентированный учет", "")    
}

System_Ext(ESB, "Брокер сообщений RMQ")

' Связи
Rel(СотрудникТочкиПродаж, 1С_АСПСП, "Ввод данных, продажа полисов")
Rel(Актуарий, УчетнаяСистема, "Анализ данных")
Rel(СотрудникДФУ, Бухгалтерия, "Отчетность")


' Связи ERP с Бухгалтерией через Шину
Rel(АС_Учет, ESB, "Полисы и предварительные расчеты", "http")
Rel(ESB, ОтражениеПолисоввБУ, "Полисы", "http")
Rel(ESB, УчетПолисов, "Полисы, Расчеты", "http")


@enduml
